use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, css_for_theme_with_class_style};

/// Build CSS for syntect class-based highlighting (light default, dark in media query).
pub fn build_syntax_css() -> String {
    let theme_set = ThemeSet::load_defaults();
    let class_style = ClassStyle::Spaced;

    let light = theme_set
        .themes
        .get("InspiredGitHub")
        .or_else(|| theme_set.themes.values().next())
        .expect("syntect ships at least one theme");
    let dark = theme_set
        .themes
        .get("base16-ocean.dark")
        .or(Some(light))
        .unwrap();

    let light_css = css_for_theme_with_class_style(light, class_style)
        .expect("syntect can emit class-style CSS for the bundled theme");
    let dark_css = css_for_theme_with_class_style(dark, class_style)
        .expect("syntect can emit class-style CSS for the bundled theme");

    let mut out = String::with_capacity(light_css.len() + dark_css.len() + 256);
    out.push_str("/* Auto-generated by mdshelf from syntect themes. */\n");
    out.push_str(&light_css);
    out.push_str("\n@media (prefers-color-scheme: dark) {\n");
    out.push_str(&dark_css);
    out.push_str("\n}\n:root[data-theme=\"dark\"] {\n");
    out.push_str(&dark_css);
    out.push_str("\n}\n");
    out
}
